### ISSUE TITLE
object should not be able to add data to become data object.

### ISSUE THREAD

**Issue by tenSunFree** [shahzadansari/RickAndMorty#20]
object should not be able to add data to become data object.
<img width="509" alt="2024-02-26_150524" src="https://github.com/shahzadansari/RickAndMorty/assets/23090085/07bfb219-8765-49a9-9f40-aac94dc67bb7">

**Comment by shahzadansari** [comment]
@tenSunFree A `data object` is identical to a regular `object` but provides a default implementation of the `toString()` function that will print its name, removing the need to override it manually, and aligning behavior with a `data class` definition.

It is now the recommended approach for `sealed class` hierarchies.


<img width="684" alt="Screenshot 2024-02-26 at 1 28 39 PM 1" src="https://github.com/shahzadansari/RickAndMorty/assets/43310446/8a1e4b37-bfa6-4e7b-8949-98c31e0fa8be">

**References:**
- https://kotlinlang.org/docs/object-declarations.html#data-objects:~:text=Just%20like%20data,the%20data%20object
- https://medium.com/@domen.lanisnik/data-objects-in-kotlin-1a549bfad657

**Comment by tenSunFree** [comment]
I learned, thank you for sharing.
