### ISSUE TITLE
About the naming of CharactersCache and CharactersService

### ISSUE THREAD

**Issue by tenSunFree** [shahzadansari/RickAndMorty#21]
Have you considered renaming the original CharactersCache and CharactersService to CharactersLocal and CharactersRemote?

Because CharactersCache currently handles SqlDriver, which is persistent data, but Cache should be more like handling global variables or memory cache, etc., which are temporary cache data.
<img width="585" alt="2024-03-04_041549" src="https://github.com/shahzadansari/RickAndMorty/assets/23090085/dd090d3d-29bc-4eab-86da-ea5837fa7169">

**Comment by shahzadansari** [comment]
`CharactersLocal` and `CharactersRemote` sounds reasonable 👍

**Comment by shahzadansari** [comment]
Refactored in https://github.com/shahzadansari/RickAndMorty/commit/728d4d2b0df2040c7b130a11fd72a5a9f8d272cf
