### ISSUE TITLE
When an item is quickly clicked multiple times on the ListScreen, multiple DetailsScreen will be displayed.

### ISSUE THREAD

**Issue by tenSunFree** [shahzadansari/RickAndMorty#22]
Have you considered adding debounceNavigation? Avoid displaying multiple DetailsScreen.
<img width="366" alt="002" src="https://github.com/shahzadansari/RickAndMorty/assets/23090085/56eb3191-60fa-4911-8bfe-d6c29efb56fc">
<img width="617" alt="001" src="https://github.com/shahzadansari/RickAndMorty/assets/23090085/17456692-507a-4368-8b4e-38ff5cfa4855">

**Comment by shahzadansari** [comment]
@tenSunFree We can enable `launchSingleTop` to allow only one instance of a destination. I have created PR #23 to fix this issue.
If we were to go with a flag to disable interaction approach, using Coroutines would be less boilerplatey IMO.

**Comment by shahzadansari** [comment]
Fixed in #23
